### ISSUE TITLE
Moodle Auto Update

### ISSUE THREAD

**Issue by wbuk** [catalyst/moodle-tool_cohortdatabase#22]
Big ask, but any chance you can update the supported version number on the moodle database to 4.3+.  Cohort Database does work on 4.3+.  We update moodle every week and Cohort Database has to be installed manually as moodle thinks it only works up to version 4.1.  If you increase the supported version to latest it will install automatically upon upgrade, saving a lot of time. Cheers.

**Comment by danmarsden** [comment]
Thanks for confirming it works in 4.3 - I've updated the version.php to state that it supports 4.3 and if the CI tests pass it should auto-deploy to the plugins db. If it doesn't, there's likely an error in the tests somewhere that will need fixing - feel free to send through a PR with any fixes too.

**Comment by acquaalta** [comment]
Hi @danmarsden,
Does the plugin work on Moodle 4.5, and if and when an official support for that version is expected?

Thanks

**Comment by danmarsden** [comment]
@acquaalta - "When will X happen" is really only a question we can answer to clients that have a commercial relationship with us. best thing for you to do is to test the plugin and report any issues you find.

I note the stats page on moodle.org lists at least 14 4.5 site have it installed:
https://moodle.org/plugins/tool_cohortdatabase/stats

thanks!

**Comment by acquaalta** [comment]
@danmarsden Thanks :-)
