### ISSUE TITLE
Email matching on sync is case sensitive

### ISSUE THREAD

**Issue by jonwitts** [catalyst/moodle-tool_cohortdatabase#3]
When running  "sudo -u www-data /usr/bin/php sync.php -v" we get a load of entries like this:

Starting cohort synchronisation...
Updated 0 cohort names/descriptions
Starting cohort database user sync
Could not find user with email = user1@domain.com
Could not find user with email = user2@domain.com

These user emails do exist in the Moodle database, however they have differing case, i.e. User1@ or uSer2@... Is it possible to get the search to do a case insensitive search against emails in the database when looking for users?

**Comment by danmarsden** [comment]
anything is "possible" - pull requests are welcome! :-)

typically in this situation organisations will do a match against Moodle username (which should already be forced to lower case.) or they will fix the case in both sides so they match.

I'm closing as this is not something we'll be working on but feel free to submit a pull request and we can review it for inclusion.

thanks!
