### ISSUE TITLE
Help needed: Nothing being sync

### ISSUE THREAD

**Issue by sam-suresh** [catalyst/moodle-tool_cohortdatabase#6]
Thank you for this plugin.
I use external database auth and the connection works. 
In the same database I have a separate table with user cohort info:
USERID, COHORTID

When execution cohort sync via scheduled task and debug enabled, It says sync completed without fetching any cohorts. No cohorts were created in Users=>Cohorts.

Any hints greatly appreciated.

Sam

**Comment by danmarsden** [comment]
Hi Sam, 

Unfortunately we are unable to provide "free" general support here. If you are looking for free moodle help the best place to ask for help is in the community forums on moodle.org.

If you would like commercial level support feel free to drop me a private email and I can provide information on our rates.

**Comment by sam-suresh** [comment]
Hi Dan!
Can you please provide your contact details.

Sam
